import type {
  Beat,
  ClarifyCardData,
  ReasoningStep,
  SourceRef,
  TabConfig,
  ThreadEntry,
} from "./types";

/* -------------------------------------------------------------------------- */
/* Reusable building blocks                                                   */
/* -------------------------------------------------------------------------- */

const TURN1 = "Re-draft the §12.4 hepatic AE narrative.";
const TURN2 = "Add a statement on resolution time.";

const csrTab: TabConfig = { id: "csr-014", kind: "md", label: "CSR-014.md", active: true };
const csrTabInactive: TabConfig = { id: "csr-014", kind: "md", label: "CSR-014.md", active: false };
const csvTabActive: TabConfig = { id: "lft", kind: "csv", label: "Phase3-LFT-Listings.csv", active: true };
const csvTabInactive: TabConfig = { id: "lft", kind: "csv", label: "Phase3-LFT-Listings.csv", active: false };
const protocolTabActive: TabConfig = { id: "protocol", kind: "pdf", label: "Aurora-IV_Protocol_v4.2", active: true, fromMap: true };
const protocolTabInactive: TabConfig = { id: "protocol", kind: "pdf", label: "Aurora-IV_Protocol_v4.2", active: false, fromMap: true };

const SRC_PHASE2_BASELINE: SourceRef = {
  kind: "md",
  file: "Phase2-CSR-007.md",
  section: "§5.2",
  expanded: true,
};
const SRC_PHASE2_BASELINE_COLLAPSED: SourceRef = {
  ...SRC_PHASE2_BASELINE,
  expanded: false,
};
const SRC_PHASE2_CROSSCHECK: SourceRef = {
  kind: "md",
  file: "Phase2-CSR-007.md",
  section: "§5.2 cross-check",
  expanded: true,
};
const SRC_PHASE2_CROSSCHECK_COLLAPSED: SourceRef = {
  ...SRC_PHASE2_CROSSCHECK,
  expanded: false,
};
const SRC_LFT: SourceRef = { kind: "csv", file: "Phase3-LFT-Listings.csv", expanded: true };
const SRC_LFT_COLLAPSED: SourceRef = { kind: "csv", file: "Phase3-LFT-Listings.csv", expanded: false };
const SRC_PROTOCOL: SourceRef = {
  kind: "pdf",
  file: "Protocol_v4.2",
  section: "§6.3",
  page: "P. 12",
  expanded: true,
};
const SRC_PROTOCOL_COLLAPSED: SourceRef = { ...SRC_PROTOCOL, expanded: false };

const Q1: ClarifyCardData = {
  qN: 1,
  total: 3,
  question: "Framing for the 2 Grade 3 cases?",
  options: [
    { letter: "A", text: "Lead with resolution." },
    { letter: "B", text: "Lead with magnitude." },
    { letter: "C", text: "Mirror Phase 2 phrasing." },
  ],
};
const Q2: ClarifyCardData = {
  qN: 2,
  total: 3,
  question: "Subgroup detail?",
  options: [
    { letter: "A", text: "Brief mention only." },
    { letter: "B", text: "Standard subgroup table." },
    { letter: "C", text: "Full table with forest plot." },
  ],
  prevAnswered: [1],
};
const Q3: ClarifyCardData = {
  qN: 3,
  total: 3,
  question: "Reference Phase 2 trial?",
  options: [
    { letter: "A", text: "Inline cross-reference." },
    { letter: "B", text: "Footnote only." },
    { letter: "C", text: "Skip." },
  ],
  prevAnswered: [1, 2],
};

/** Helper: thread starting with the user's turn-1 prompt. */
const turn1Prompt: ThreadEntry = { kind: "user", text: TURN1, timestamp: "14:03" };

/* -------------------------------------------------------------------------- */
/* Reasoning step factories                                                   */
/* -------------------------------------------------------------------------- */

function step(
  n: 1 | 2 | 3 | 4,
  caption: string,
  status: "active" | "done",
  source?: SourceRef
): ReasoningStep {
  return { n, total: 4, caption, status, source };
}

const STEP1_ACTIVE = step(1, "Reading Phase 2 hepatic AE baseline", "active", SRC_PHASE2_BASELINE);
const STEP1_DONE = step(1, "Read Phase 2 hepatic AE baseline", "done", SRC_PHASE2_BASELINE_COLLAPSED);
const STEP2_ACTIVE = step(2, "Pulling LFT rows where ALT > 3×ULN", "active", SRC_LFT);
const STEP2_DONE = step(2, "Pulled LFT rows where ALT > 3×ULN", "done", SRC_LFT_COLLAPSED);
const STEP2_DONE_EXPANDED = step(2, "Pulled LFT rows where ALT > 3×ULN", "done", SRC_LFT);
const STEP3_ACTIVE = step(3, "Cross-checking Phase 2 hepatic findings", "active", SRC_PHASE2_CROSSCHECK);
const STEP3_DONE = step(3, "Cross-checked Phase 2 hepatic findings", "done", SRC_PHASE2_CROSSCHECK_COLLAPSED);
const STEP4_ACTIVE = step(4, "Reconciling FDA / EMA divergence on resolution time", "active", SRC_PROTOCOL);
const STEP4_DONE = step(4, "Reconciled FDA / EMA divergence on resolution time", "done", SRC_PROTOCOL_COLLAPSED);

/* -------------------------------------------------------------------------- */
/* Beats                                                                      */
/* -------------------------------------------------------------------------- */

export const BEATS: Beat[] = [
  // ---------- Phase A · Prompt entry ----------
  {
    id: "v2-0",
    paperId: "948-0",
    label: "Idle",
    cta: "composer field",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: null,
    thread: [
      { kind: "peer-text", text: "How can I help with §12.4?", timestamp: "14:02" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-0a",
    paperId: "998-0",
    label: "Prompt typed",
    cta: "send button",
    composer: { mode: "typed", value: TURN1 },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: null,
    thread: [{ kind: "peer-text", text: "How can I help with §12.4?", timestamp: "14:02" }],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-0b",
    paperId: "9DM-0",
    label: "User bubble in copilot",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: null,
    thread: [turn1Prompt],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-0c",
    paperId: "9UA-0",
    label: "Thinking…",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Thinking…", thinking: true, timestamp: "14:03" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-0d",
    paperId: "9YY-0",
    label: "Three quick choices",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase B · Three clarify questions ----------
  {
    id: "v2-1",
    paperId: "9O5-0",
    label: "Q1 unanswered",
    cta: "option B",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: Q1 },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-1a",
    paperId: "A8L-0",
    label: "Q1 selected — Lead with magnitude",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: { ...Q1, selected: "B" } },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-2",
    paperId: "AIX-0",
    label: "Q2 unanswered",
    cta: "option B",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: Q2 },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-2a",
    paperId: "AU3-0",
    label: "Q2 selected — Standard subgroup table",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: { ...Q2, selected: "B" } },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-3",
    paperId: "BBK-0",
    label: "Q3 unanswered",
    cta: "option A",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: Q3 },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-3a",
    paperId: "BHP-0",
    label: "Q3 selected — Inline cross-reference",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "Three quick choices before I draft.", timestamp: "14:03" },
      { kind: "clarify-card", data: { ...Q3, selected: "A" } },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-3b",
    paperId: "BWJ-0",
    label: "3/3 answered — handing off to reasoning",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "3/3 questions answered. Reasoning across sources…", timestamp: "14:03" },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase C · Reasoning streams ----------
  {
    id: "v2-3c",
    paperId: "GMV-0",
    label: "Summary pill appears",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "peer-text", text: "3/3 questions answered. Reasoning across sources…", timestamp: "14:03" },
      { kind: "summary-pill" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4a",
    paperId: "HLV-0",
    label: "Step 1 · Reading Phase 2 §5.2",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_ACTIVE] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4b",
    paperId: "HBZ-0",
    label: "Step 2 · Pulling LFT rows",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_ACTIVE] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4c",
    paperId: "I13-0",
    label: "Step 2 ✓ (rows still expanded)",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE_EXPANDED] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4d",
    paperId: "II8-0",
    label: "Steps 1-2 ✓ collapsed",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4e",
    paperId: "INT-0",
    label: "Step 3 · Cross-checking Phase 2",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_ACTIVE] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4f",
    paperId: "ISI-0",
    label: "Step 3 ✓",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_DONE] },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4g",
    paperId: "IWY-0",
    label: "Step 4 · Reconciling FDA/EMA",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_DONE, STEP4_ACTIVE] },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase D · Drafting ----------
  {
    id: "v2-4h",
    paperId: "J29-0",
    label: "All steps ✓ — drafting 3 options",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing", sublabel: "drafting 3 options" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_DONE, STEP4_DONE] },
      { kind: "drafting-text" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4i",
    paperId: "J75-0",
    label: "Reasoning collapsed to pill",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing", sublabel: "drafting 3 options" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "drafting-text" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-4j",
    paperId: "JON-0",
    label: "Settle (handoff to carousel)",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "preparing", sublabel: "drafting 3 options" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "drafting-text" },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase E · Variant carousel ----------
  {
    id: "v2-5",
    paperId: "JBZ-0",
    label: "v1 of 3 · conservative",
    cta: "▸ next",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "narrative-carousel", current: "v1" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "peer-text", text: "Three framings drafted. Cycle to compare.", timestamp: "14:03" },
      { kind: "narrative-carousel-card", current: "v1" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-6",
    paperId: "JTR-0",
    label: "v2 of 3 · direct",
    cta: "▸ next",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "narrative-carousel", current: "v2" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "peer-text", text: "Three framings drafted. Cycle to compare.", timestamp: "14:03" },
      { kind: "narrative-carousel-card", current: "v2" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-7",
    paperId: "K0M-0",
    label: "v3 of 3 · comparative",
    cta: "accept ✓",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc" },
    workingBlock: { kind: "narrative-carousel", current: "v3" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "peer-text", text: "Three framings drafted. Cycle to compare.", timestamp: "14:03" },
      { kind: "narrative-carousel-card", current: "v3" },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase F · Accept v3 + reasoning revisit ----------
  {
    id: "v2-7a",
    paperId: "KCS-0",
    label: "v3 accepted — suggestion pills appear",
    cta: "Reasoned pill OR suggestion",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [
      { label: "Add a statement on resolution time." },
      { label: "Compare to Phase 2 outcomes" },
    ],
    modal: null,
  },
  {
    id: "v2-7b",
    paperId: "KKW-0",
    label: "Reasoning re-expanded",
    cta: "step 2 csv chip",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill", expanded: true },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_DONE, STEP4_DONE] },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [
      { label: "Add a statement on resolution time." },
      { label: "Compare to Phase 2 outcomes" },
    ],
    modal: null,
  },
  {
    id: "v2-7c",
    paperId: "KUO-0",
    label: "csv source rows expanded inline",
    cta: "Open in editor",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill", expanded: true },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE_EXPANDED, STEP3_DONE, STEP4_DONE] },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [
      { label: "Add a statement on resolution time." },
      { label: "Compare to Phase 2 outcomes" },
    ],
    modal: null,
  },
  {
    id: "v2-7d",
    paperId: "MD9-0",
    label: "csv rows collapsed back",
    cta: "csv chip",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill", expanded: true },
      { kind: "reasoning-steps", steps: [STEP1_DONE, STEP2_DONE, STEP3_DONE, STEP4_DONE] },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [
      { label: "Add a statement on resolution time." },
      { label: "Compare to Phase 2 outcomes" },
    ],
    modal: null,
  },

  // ---------- Phase G · csv as tab + side-by-side ----------
  {
    id: "v2-10",
    paperId: "M01-0",
    label: "csv opened as new tab",
    cta: "side-by-side",
    composer: { mode: "idle" },
    tabs: [csrTabInactive, csvTabActive],
    sideBySide: false,
    editorMode: { kind: "csv-listing" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-11",
    paperId: "MUD-0",
    label: "Side-by-side csr | csv",
    cta: "× csv tab",
    composer: { mode: "idle" },
    tabs: [csrTabInactive, csvTabActive],
    sideBySide: true,
    editorMode: { kind: "side-by-side" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [
      { label: "Filter to Grade 3 only" },
      { label: "Group by site" },
    ],
    modal: null,
  },

  // ---------- Phase H · Second prompt + wording carousel ----------
  {
    id: "v2-h-clean",
    paperId: "OFC-0",
    label: "Split closed — back to clean",
    cta: "composer (turn 2)",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-h-clean2",
    paperId: "NN2-0",
    label: "Settle (clean)",
    composer: { mode: "typed", value: TURN2 },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-h-2",
    paperId: "OL2-0",
    label: "Turn-2 prompt sent + Thinking",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      { kind: "peer-text", text: "Thinking…", thinking: true, timestamp: "14:03" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-h-3",
    paperId: "OON-0",
    label: "Pulling resolution time data",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      {
        kind: "single-step",
        caption: "Pulling resolution time data",
        status: "active",
        source: SRC_LFT,
      },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-h-4",
    paperId: "OXS-0",
    label: "Pulled ✓",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      {
        kind: "single-step",
        caption: "Pulled resolution time data",
        status: "done",
        source: SRC_LFT_COLLAPSED,
      },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-h-5",
    paperId: "P2J-0",
    label: "FDA / EMA differ — pick",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      {
        kind: "single-step",
        caption: "Pulled resolution time data",
        status: "done",
        source: SRC_LFT_COLLAPSED,
      },
      {
        kind: "peer-text",
        text:
          "While cross-checking, I found FDA and EMA word resolution time differently. Which would you like to proceed with?",
        timestamp: "14:03",
      },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-12",
    paperId: "P72-0",
    label: "v1 of 2 · FDA wording",
    cta: "▸ next",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: { kind: "wording-carousel", current: "fda" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      {
        kind: "single-step",
        caption: "Pulled resolution time data",
        status: "done",
        source: SRC_LFT_COLLAPSED,
      },
      {
        kind: "peer-text",
        text: "Two regional phrasings — pick one.",
        timestamp: "14:03",
      },
      { kind: "wording-carousel-card", current: "fda" },
    ],
    suggestions: [],
    modal: null,
  },
  {
    id: "v2-13",
    paperId: "PAZ-0",
    label: "v2 of 2 · EMA wording",
    cta: "accept ✓",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3" },
    workingBlock: { kind: "wording-carousel", current: "ema" },
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      {
        kind: "single-step",
        caption: "Pulled resolution time data",
        status: "done",
        source: SRC_LFT_COLLAPSED,
      },
      {
        kind: "peer-text",
        text: "Two regional phrasings — pick one.",
        timestamp: "14:03",
      },
      { kind: "wording-carousel-card", current: "ema" },
    ],
    suggestions: [],
    modal: null,
  },

  // ---------- Phase I · Accept EMA + traceability ----------
  {
    id: "v2-13a",
    paperId: "PHY-0",
    label: "EMA accepted",
    cta: "Trace the citations",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3", committedEMA: true },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      { kind: "accepted-pill", label: "Accepted · EMA wording" },
    ],
    suggestions: [
      { label: "Open Protocol §6.3 for monitoring rules" },
      { label: "Trace the citations" },
    ],
    modal: null,
  },
  {
    id: "v2-13b",
    paperId: "PO7-0",
    label: "Settle — pre-map",
    cta: "map icon",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3", committedEMA: true },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      { kind: "accepted-pill", label: "Accepted · EMA wording" },
    ],
    suggestions: [
      { label: "Open Protocol §6.3 for monitoring rules" },
      { label: "Trace the citations" },
    ],
    modal: null,
  },
  {
    id: "v2-14",
    paperId: "PTV-0",
    label: "Traceability map",
    cta: "Protocol_v4.2 node",
    composer: { mode: "idle" },
    tabs: [csrTab],
    sideBySide: false,
    editorMode: { kind: "csr-doc", commitedNarrative: "v3", committedEMA: true },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      { kind: "accepted-pill", label: "Accepted · EMA wording" },
    ],
    suggestions: [],
    modal: "map",
  },
  {
    id: "v2-16",
    paperId: "QAN-0",
    label: "Protocol PDF as tab",
    composer: { mode: "idle" },
    tabs: [csrTabInactive, protocolTabActive],
    sideBySide: false,
    editorMode: { kind: "pdf-protocol" },
    workingBlock: null,
    thread: [
      turn1Prompt,
      { kind: "summary-pill" },
      { kind: "reasoned-pill" },
      { kind: "accepted-pill", label: "Accepted · v3 comparative" },
      { kind: "user", text: TURN2, timestamp: "14:03" },
      { kind: "accepted-pill", label: "Accepted · EMA wording" },
      { kind: "peer-text", text: "Opened Protocol_v4.2 from the map.", timestamp: "14:03" },
    ],
    suggestions: [],
    modal: null,
  },
];
